breaks heroku
ActionView::Template::Error (undefined method `chr' for
"Alberta":String):
   10:
      11: <% @cadets.each do |cadet| %>
         12:   <tr>
            13:         <td><%= cadet.name %></td>
               14:     <td><%= cadet.platoon %></td>
                  15:     <td><%= cadet.email %></td>
                     16:     <td><%= link_to 'Show', cadet %></td>
                      app/models/cadet.rb:11:in `name'
                       app/views/cadets/index.html.erb:13:in
                       `_app_views_cadets_index_html_erb___1394683667_70002941858000_0'
                        app/views/cadets/index.html.erb:11:in
                        `_app_views_cadets_index_html_erb___1394683667_70002941858000_0'
                         app/controllers/cadets_controller.rb:7:in
                         `index'

Revert "even better method of getting first initial"

This reverts commit 6318bdd3dc33c2c4c83805e8a0e930851bae64de.